/** Design tokens lifted verbatim from the Stitch mockups. */
/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "#f8f9ff",
        "inverse-primary": "#84d4d3",
        "surface-container": "#e5eeff",
        "inverse-on-surface": "#eaf1ff",
        "on-secondary-fixed": "#131b2e",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#eff4ff",
        "outline-variant": "#bec9c8",
        "on-secondary-container": "#5c647a",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#bec6e0",
        "surface-dim": "#cbdbf5",
        "inverse-surface": "#213145",
        "on-surface-variant": "#3e4948",
        "primary-fixed": "#a0f0f0",
        "on-background": "#0b1c30",
        primary: "#005454",
        "error-container": "#ffdad6",
        tertiary: "#00554b",
        "on-secondary-fixed-variant": "#3f465c",
        "primary-fixed-dim": "#84d4d3",
        "on-primary-container": "#9dedec",
        "surface-tint": "#016a6a",
        "tertiary-container": "#006f63",
        "surface-bright": "#f8f9ff",
        "on-tertiary-fixed": "#00201c",
        "on-primary-fixed": "#002020",
        "surface-container-high": "#dce9ff",
        "tertiary-fixed-dim": "#3cddc7",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#005047",
        "surface-variant": "#d3e4fe",
        secondary: "#565e74",
        "secondary-container": "#dae2fd",
        "primary-container": "#0d6e6e",
        "on-primary-fixed-variant": "#004f50",
        "on-surface": "#0b1c30",
        "on-primary": "#ffffff",
        outline: "#6e7979",
        error: "#ba1a1a",
        "on-tertiary-container": "#5df6e0",
        "surface-container-highest": "#d3e4fe",
        "on-secondary": "#ffffff",
        surface: "#f8f9ff",
        "tertiary-fixed": "#62fae3",
        "secondary-fixed": "#dae2fd",
        "surface-container-lowest": "#ffffff",
      },
      borderRadius: { DEFAULT: "0.25rem", lg: "0.5rem", xl: "0.75rem", "2xl": "1rem", full: "9999px" },
      spacing: {
        "space-2xs": "0.25rem",
        "space-xs": "0.5rem",
        "space-sm": "0.75rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-2xl": "3rem",
        "space-3xl": "4rem",
        "margin-mobile": "1rem",
        "margin-tablet": "2rem",
        "margin-desktop": "3rem",
      },
      fontFamily: { sans: ["Inter", "system-ui", "sans-serif"] },
      fontSize: {
        display: ["44px", { lineHeight: "52px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "currency-display": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.005em", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        caption: ["11px", { lineHeight: "14px", letterSpacing: "0.03em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
