"""linked_accounts.provider column

Revision ID: c742fe8cd5d2
Revises: c9fc3d378f4f
Create Date: 2026-09-10 18:14:37.329217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c742fe8cd5d2'
down_revision: Union[str, Sequence[str], None] = 'c9fc3d378f4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('linked_accounts', sa.Column('provider', sa.String(), server_default='mock', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('linked_accounts', 'provider')
    # ### end Alembic commands ###
