"""unique linked_account per user+provider_item

Revision ID: c9fc3d378f4f
Revises: 51606856691b
Create Date: 2026-09-10 13:14:11.225631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9fc3d378f4f'
down_revision: Union[str, Sequence[str], None] = '51606856691b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_linked_accounts_user_id_provider_item_id', 'linked_accounts', ['user_id', 'provider_item_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_linked_accounts_user_id_provider_item_id', 'linked_accounts', type_='unique')
    # ### end Alembic commands ###
