"""add unique constraint on transactions

Revision ID: f0f436e5d83f
Revises: 5a5601e6f983
Create Date: 2026-09-07 18:25:10.464457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0f436e5d83f'
down_revision: Union[str, Sequence[str], None] = '5a5601e6f983'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_transactions_account_id_provider_transaction_id', 'transactions', ['account_id', 'provider_transaction_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_transactions_account_id_provider_transaction_id', 'transactions', type_='unique')
    # ### end Alembic commands ###
